# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.cache/wt [current_project]
set_property parent.project_path C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.srcs/sources_1/imports/CMPS375Lab1/Adder1.vhd
  C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.srcs/sources_1/new/adder4.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.srcs/constrs_1/imports/CMPS375Lab1/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/PersonalData/Repos/cmps375/Labs/Lab2/lab2Josh/lab2Josh.srcs/constrs_1/imports/CMPS375Lab1/Nexys4DDR_Master.xdc]


synth_design -top adder4 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef adder4.dcp

catch { report_utilization -file adder4_utilization_synth.rpt -pb adder4_utilization_synth.pb }
